<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Proyecto_Integrador</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ControlesUsuario\Enfermedades Caballos\Enfermedades.cs" />
    <Compile Remove="ControlesUsuario\Enfermedades Caballos\Enfermedades.Designer.cs" />
    <Compile Remove="ControlesUsuario\Enfermedades Caballos\frmTratamiento.cs" />
    <Compile Remove="ControlesUsuario\Enfermedades Caballos\frmTratamiento.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="ControlesUsuario\Enfermedades Caballos\Enfermedades.resx" />
    <EmbeddedResource Remove="ControlesUsuario\Enfermedades Caballos\frmTratamiento.resx" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Datos\caballos.json" />
    <None Remove="Datos\tratamientos.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Datos\caballos.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Datos\tratamientos.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>